import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AlertProvider } from "@/context/AlertProvider";
import { ConfigProvider } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider
      theme={{
        components: {
          Input: {
            activeBorderColor: "#492DC2",
            hoverBorderColor: "#492DC2",
            colorPrimaryHover: "#492DC2",
          },
          Switch: {
            colorPrimary: "#492DC2",
            colorPrimaryHover: "#492DC2",
          },
          DatePicker: {
            activeBorderColor: "#492DC2",
            hoverBorderColor: "#492DC2",
            colorPrimary: "#492DC2",
            colorPrimaryBorder: "#492DC2",
          },
          InputNumber: {
            activeBorderColor: "#492DC2",
            hoverBorderColor: "#492DC2",
            colorText: "#492DC2",
            handleHoverColor: "#492DC2",
          },
          Select: {
            hoverBorderColor: "#492DC2",
            activeBorderColor: "#492DC2",
            optionSelectedBg: "#DDCEFB",
          },
        },
      }}
    >
      <AlertProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </html>
      </AlertProvider>
    </ConfigProvider>
  );
}
